server:
  port: 9054
spring:  
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shorten_url 
    username: postgres
    password: thirumal
    pool:
      enabled: true
      initial-size: 1
      max-size: 20
      max-idle-time: 30m
redirect:
  default-url: https://www.google.com