server:
  port: 9054
spring:  
  r2dbc:
    url: r2dbc:postgresql://172.31.21.199:5432/shorten_url 
    username: postgres
    password: Thirumal
    pool:
      enabled: true
      initial-size: 1
      max-size: 20
      max-idle-time: 30m